@Management.Clean.Api_HostAddress = http://localhost:7112
@token=mytoken32423423

POST {{Management.Clean.Api_HostAddress}}/api/Auth/login
Content-Type: application/json
Accept: application/json
{
    "Email": "user@localhost.com",
    "Password": "P@ssword1"
}
{{
    exports.token = response.parsedBody.token
}}

GET {{Management.Clean.Api_HostAddress}}/api/LeaveTypes
Accept: application/json
Authorization: Bearer {{token}}

GET {{Management.Clean.Api_HostAddress}}/api/LeaveAllocations
Accept: application/json
Authorization: Bearer {{token}}

GET {{Management.Clean.Api_HostAddress}}/api/LeaveRequests
Accept: application/json
Authorization: Bearer {{token}}

GET {{Management.Clean.Api_HostAddress}}/api/LeaveTypes/1
Accept: application/json
Authorization: Bearer {{token}}

DELETE {{Management.Clean.Api_HostAddress}}/api/LeaveTypes/2
Accept: application/json
Authorization: Bearer {{token}}

DELETE {{Management.Clean.Api_HostAddress}}/api/LeaveAllocations/3
Accept: application/json
Authorization: Bearer {{token}}

DELETE {{Management.Clean.Api_HostAddress}}/api/LeaveRequests/1
Accept: application/json
Authorization: Bearer {{token}}

PUT {{Management.Clean.Api_HostAddress}}/api/LeaveTypes/2
Content-Type: application/json
{
    "Name": "Test1",
    "DefaultDays": 3
}

POST {{Management.Clean.Api_HostAddress}}/api/LeaveTypes
Content-Type: application/json
{
    "Name": "Test1",
    "DefaultDays": 2
}

POST {{Management.Clean.Api_HostAddress}}/api/LeaveAllocations
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "LeaveTypeId": 1
}

POST {{Management.Clean.Api_HostAddress}}/api/LeaveRequests
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "StartDate": "2025-09-01",
    "EndDate": "2025-09-05",
    "LeaveTypeId": 1,
    "RequestComments": "Going on vacation to the beach with family."
}

PUT {{Management.Clean.Api_HostAddress}}/api/LeaveRequests/UpdateApproval
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "Id": 5,
    "Approved": true
}

PUT {{Management.Clean.Api_HostAddress}}/api/LeaveRequests/CancelRequest
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "Id": 5
}
###